
.include <bsd.own.mk>

LIB=	diskimage
CSTD?=	c99

SRCS=	diskimage.c fileinterface.c filemap.c vhdbat.c vhdchecksum.c vhdfooter.c vhdheader.c vhdparser.c vhdserialization.c vmdkdescriptorfile.c vmdkextentdescriptor.c
INCS=	diskimage.h
MAN=	diskimage.3

CFLAGS= -g


SHLIB_MAJOR=	1

.include <bsd.lib.mk>

